### ISSUE TITLE
[Feature?]: Allow HS APIs to support class merging in options

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1192]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Right now in order to merge classes if you want to do custom stuff in a CSS Module scenario, you need to do some pretty intensive work destructuring API return props to get the className, etc. It would be nice if all the APIs accepted a `classes` prop that would merge it's value with the HS classes.

### Examples 🌈

Global CSS (already supported):
```css
/* global button.css */

/* overwrite all Pando btns by using the empty class provided by Pando */
.ps-btn {
  width: 100%;
}
```

CSS-in-JS (already supported) - not really valid use of tech

CSS Modules (already supported - but hard to use):
```javascript
const { button } = getButtonProps()
const { className, ...otherBtnProps }  = button
const classes = `${customLocalClass} ${className}`

return <button className={classes} {...otherBtnProps>Yucky</button>
```

#### Preferred Solution:
```javascript
const { button }  = getButtonProps({ classes: [styles.customClass, 'static-class'] })
```

### Motivation 🔦

Headless-styles
