### ISSUE TITLE
[Feature?]: pando cli: html & css files

### ISSUE THREAD

**Issue by kathydlavoie-ps** [pluralsight/pando#1756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [ ]  Update the index.html `head` tag
  - [ ] The CLI should update the `head` of the `index.html` file to include the following:
  - [ ] _NOTE: This should be added **before** any other tag in the `head`._
```html
<link
  rel="preload"
  href="https://fonts.pluralsight.com/ps-tt-commons/v1/ps-tt-commons-variable-roman.woff2"
  as="font"
  type="font/woff2"
  crossorigin
/>
```
> Note: Some frameworks like Next.js will have font helpers to preload fonts. This should be used instead of the above. See the [Panda documentation](https://panda-css.com/docs/guides/fonts#setup) for more details.

___

- [ ] Create `pando.entry.css` file
  - [ ] The CLI should create a `pando.entry.css` file in the `src` directory of the project. This file should be the main CSS file for the project. For the file contents, the CLI should write Step 5 of the PostCSS setup documentation to the file along with some custom font setup:
```css
@font-face {
  font-display: swap;
  font-family: 'PS Commons';
  font-style: normal;
  font-weight: 500 800;
  src: url('https://fonts.pluralsight.com/ps-tt-commons/v1/ps-tt-commons-variable-roman.woff2')
    format('woff-variations');
}

@font-face {
  font-display: swap;
  font-family: 'DM Mono';
  font-style: normal;
  font-weight: 400;
  src: url('https://fonts.pluralsight.com/dm-mono/v1/dm-mono-regular.ttf')
    format('truetype');
}

:root {
  --font-pando: 'PS Commons', 'Gotham SSm A', 'Gotham SSm B', Arial, sans-serif;
  --font-pando-mono: 'DM Mono', 'Fira Code', 'Operator Mono', 'Source Code Pro', monospace;
}
```
