### ISSUE TITLE
[Feature?]: transformCSStoTS to support CSS Modules

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/pando#675]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Replace `composes` properties with the contents of the referenced class(es).
Other properties within the rule should override any from the composed class(es).
Multiple classes should be applied sequentially, with the latter overwriting the former.

**Should fully support all CSS Modules features. Should make it a new plugin probably.**

### Examples 🌈

Given:
```css
.classA {
  border: 1px solid;
  color: red;
  padding: .5em;
}

.classB {
  background-color: white;
  padding: 1rem;
}

.classC {
  composes: classA classB;
  color: blue;
}
```

`.classC` will become
```js
classC: {
  border: '1px solid',
  backgroundColor: 'white',
  color: 'blue',
  padding: '1rem',
}
```

### Motivation 🔦

Currently in the JS APIs, we are manually assigning the composed classes.  Allowing the tool to handle this will reduce the size of our code, as well as opportunity for errors.  It will also improve the consistency between the CSS and JS API outputs, and reduce maintenance by consolidating control.
